---
- hosts: anshosts
  become: yes
  tasks:
  - name: update ubuntu and confirm iptables is present
    apt:
      update_cache: yes
      name: iptables
      state: latest

## iptables save might need to be installed

  - name: flush IP tables
    ansible.builtin.iptables:
    flush: yes

  - name: add loopback
    ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

  - name: add established connections
    ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

  - name: add port 22
    ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

  - name: drop all other connections
    ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

  - name: save firewall rules
    ansible.builtin.shell: iptables-save
