# basic options
title: The Cat Chronicles KB
author: Salem the cat
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
minima:
  skin: dark
